# Remember to run xhost +local:root
version: '3'
services:
  head_0:
    build:
      context: .
      dockerfile: Dockerfile.linux
    ports:
      - "5000:5000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
      - LCD_NUMBER=0

  head_1:
    build:
      context: .
      dockerfile: Dockerfile.linux
    ports:
      - "5001:5001"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
      - LCD_NUMBER=1
  head_2:
    build:
      context: .
      dockerfile: Dockerfile.linux
    ports:
      - "5002:5002"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
      - LCD_NUMBER=2
  head_3:
    build:
      context: .
      dockerfile: Dockerfile.linux
    ports:
      - "5003:5003"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
      - LCD_NUMBER=3
