FROM raspbian/stretch

RUN apt-get update && apt-get install -y \
  ruby \
  ruby-dev \
  automake \
  libtool && \
  rm -rf /var/lib/apt/lists/*

RUN gem install --no-ri --no-rdoc ssdp eventmachine

RUN mkdir -p /opt/ansi_scroller
COPY bin /opt/ansi_scroller/bin
COPY lib /opt/ansi_scroller/lib

WORKDIR /opt/ansi_scroller
CMD ["ruby", "bin/ansi_server.rb"]
